## Numpy 

In [6]:
import numpy as np 

### Focusing on Data Types & Attributes 

In [7]:
# Numpy's main datatypes: ndarray 

In [8]:
a1 = np.array([1,2,1,2,54,5])

In [9]:
a1

array([ 1,  2,  1,  2, 54,  5])

In [10]:
type(a1)

numpy.ndarray

In [11]:
# 2 dimensional arr 

In [12]:
a2 = np.array([[1,2,3,5,4,88], [5,8,7,5,45,4758]])

In [13]:
a2

array([[   1,    2,    3,    5,    4,   88],
       [   5,    8,    7,    5,   45, 4758]])

In [14]:
type(a2)

numpy.ndarray

In [15]:
a3 = np.array([[[12,2,54,5], [5,5,4,5], [7,8,5,75]]])

In [16]:
a3

array([[[12,  2, 54,  5],
        [ 5,  5,  4,  5],
        [ 7,  8,  5, 75]]])

In [17]:
type(a3)

numpy.ndarray

In [18]:
# Getting the shape of the arrays 
a1.shape, a2.shape, a3.shape

((6,), (2, 6), (1, 3, 4))

In [19]:
# Getting the dimension of the array 
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [20]:
# Size of the data (number of elements)
a1.size, a2.size, a3.size

(6, 12, 12)

In [21]:
# Crearting a data frame from a Numpy Array 

import pandas as pd

In [22]:
# df_a1 = pd.DataFrame(a1)
# df_a2 = pd.DataFrame(a2)
# df_a3 = pd.DataFrame(a3)

In [23]:
# df_a1,  
# df_a2, 
# df_a3

In [24]:
df = pd.DataFrame(a2)
df

0  1  2  3   4     5
0  1  2  3  5   4    88
1  5  8  7  5  45  4758

### Creating Arrays: Numpy's 

In [25]:
# Custom sample arr 

sample_arr = np.array([1,5,47,54,])
sample_arr, "|" ,  sample_arr.dtype

(array([ 1,  5, 47, 54]), '|', dtype('int64'))

In [26]:
# Creating array with prefilled data 

ones = np.ones((2, 3))
ones
# pd.DataFrame(ones)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
ones.dtype, type(ones)

(dtype('float64'), numpy.ndarray)

In [28]:
# New Array with Zeros 

zeros = np.zeros((2, 5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
pd.DataFrame(zeros)

0    1    2    3    4
0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0

In [30]:
# Creating a range arr 

range_arr = (np.arange(0, 10, 2), np.arange(0, 20, 4))
range_arr

(array([0, 2, 4, 6, 8]), array([ 0,  4,  8, 12, 16]))

In [31]:
pd.DataFrame(range_arr)

0  1  2   3   4
0  0  2  4   6   8
1  0  4  8  12  16

In [32]:
random_arr = np.random.randint(0, 30, size=(3,5))
random_arr

array([[13,  8, 26,  5, 28],
       [11,  6,  5, 24,  7],
       [ 9,  6,  2, 12,  7]])

In [33]:
pd.DataFrame(random_arr)

0  1   2   3   4
0  13  8  26   5  28
1  11  6   5  24   7
2   9  6   2  12   7

In [34]:
random_arr.size, random_arr.dtype

(15, dtype('int64'))

In [35]:
random_arr2 = np.random.random(size=(3,5))
random_arr2

array([[0.35883666, 0.56299358, 0.6599501 , 0.92747002, 0.27099229],
       [0.30029373, 0.99753263, 0.35014614, 0.40232704, 0.14245219],
       [0.7985399 , 0.44934698, 0.87389458, 0.15698518, 0.26741025]])

In [36]:
pd.DataFrame(random_arr2)

0         1         2         3         4
0  0.358837  0.562994  0.659950  0.927470  0.270992
1  0.300294  0.997533  0.350146  0.402327  0.142452
2  0.798540  0.449347  0.873895  0.156985  0.267410

In [37]:
random_arr3 = np.random.rand(3, 5)
random_arr3

array([[0.54550372, 0.25462466, 0.08563068, 0.31292455, 0.06261281],
       [0.93955759, 0.05464836, 0.23592273, 0.97864916, 0.27561843],
       [0.15232226, 0.33463745, 0.84081424, 0.32221779, 0.0618291 ]])

In [38]:
pd.DataFrame(random_arr3)

0         1         2         3         4
0  0.545504  0.254625  0.085631  0.312925  0.062613
1  0.939558  0.054648  0.235923  0.978649  0.275618
2  0.152322  0.334637  0.840814  0.322218  0.061829

In [39]:
# Pseudo random numbers: helpful when you want to generate reproducable random numbers 
# If we dont't seed the random no then it will generate new ones everytime they get triggered 

np.random.seed(seed=0)

random_arr4 = np.random.randint(0,20, size=(4,5))
random_arr4

array([[12, 15,  0,  3,  3],
       [ 7,  9, 19, 18,  4],
       [ 6, 12,  1,  6,  7],
       [14, 17,  5, 13,  8]])

### Viewing Metrices and Arrays 

In [40]:
# Unique no. in an array 

np.unique(random_arr4)

array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 12, 13, 14, 15, 17, 18, 19])

In [41]:
random_arr4

array([[12, 15,  0,  3,  3],
       [ 7,  9, 19, 18,  4],
       [ 6, 12,  1,  6,  7],
       [14, 17,  5, 13,  8]])

In [42]:
random_arr

array([[13,  8, 26,  5, 28],
       [11,  6,  5, 24,  7],
       [ 9,  6,  2, 12,  7]])

In [43]:
random_arr2

array([[0.35883666, 0.56299358, 0.6599501 , 0.92747002, 0.27099229],
       [0.30029373, 0.99753263, 0.35014614, 0.40232704, 0.14245219],
       [0.7985399 , 0.44934698, 0.87389458, 0.15698518, 0.26741025]])

In [44]:
random_arr3

array([[0.54550372, 0.25462466, 0.08563068, 0.31292455, 0.06261281],
       [0.93955759, 0.05464836, 0.23592273, 0.97864916, 0.27561843],
       [0.15232226, 0.33463745, 0.84081424, 0.32221779, 0.0618291 ]])

In [45]:
random_arr4

array([[12, 15,  0,  3,  3],
       [ 7,  9, 19, 18,  4],
       [ 6, 12,  1,  6,  7],
       [14, 17,  5, 13,  8]])

### Manipulating and Comparing Arrays 

In [47]:
# Arithematic

In [48]:
a1

array([ 1,  2,  1,  2, 54,  5])

In [50]:
random_arr

array([[13,  8, 26,  5, 28],
       [11,  6,  5, 24,  7],
       [ 9,  6,  2, 12,  7]])

In [51]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [52]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [59]:
new_ones = np.ones(6)

In [60]:
new_ones

array([1., 1., 1., 1., 1., 1.])

In [61]:
a1 + new_ones

array([ 2.,  3.,  2.,  3., 55.,  6.])

In [62]:
a1 - new_ones

array([ 0.,  1.,  0.,  1., 53.,  4.])